# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-29 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_integralgoods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integralgoods',
            name='user',
        ),
    ]
