# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-29 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='integral',
            field=models.IntegerField(default=0, verbose_name='用户积分'),
        ),
    ]
