# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-01 15:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Couponcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('coupon_id', models.CharField(max_length=20, verbose_name='优惠券编号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='获取优惠券用户')),
            ],
            options={
                'verbose_name': '优惠券列表',
                'verbose_name_plural': '优惠券列表',
                'db_table': 'tb_coupon',
            },
        ),
    ]
